[[types]]
name = "convention"
plural = "convention"
dir = "docs/convention"
prefix = "CONVENTION"
icon = "📜"
singleton = true

[[types]]
name = "dictum"
plural = "dicta"
dir = "docs/convention"
prefix = "DICTUM"
icon = "⚖"
parent_type = "convention"

[[types]]
name = "spec"
plural = "specs"
dir = "docs/specs"
prefix = "SPEC"
icon = "📋"

[[types]]
name = "rfc"
plural = "rfcs"
dir = "docs/rfcs"
prefix = "RFC"
icon = "●"

[[types]]
name = "story"
plural = "stories"
dir = "docs/stories"
prefix = "STORY"
icon = "▲"

[[types]]
name = "iteration"
plural = "iterations"
dir = "docs/iterations"
prefix = "ITERATION"
icon = "◆"

[[types]]
name = "adr"
plural = "adrs"
dir = "docs/adrs"
prefix = "ADR"
icon = "■"

[[types]]
name = "audit"
plural = "audits"
dir = "docs/audits"
prefix = "AUDIT"
icon = "🔍"

[github]
repo = 'jkaloger/lazyspec'

[templates]
dir = ".lazyspec/templates"

[naming]
pattern = "{type}-{n:03}-{title}.md"

